export const DATAFORSEO_LANGUAGES = [
	{ name: "Albanian", code: "sq" },
	{ name: "Arabic", code: "ar" },
	{ name: "Armenian", code: "hy" },
	{ name: "Azeri", code: "az" },
	{ name: "Bengali", code: "bn" },
	{ name: "Bosnian", code: "bs" },
	{ name: "Bulgarian", code: "bg" },
	{ name: "Chinese (Simplified)", code: "zh-CN" },
	{ name: "Chinese (Traditional)", code: "zh-TW" },
	{ name: "Croatian", code: "hr" },
	{ name: "Czech", code: "cs" },
	{ name: "Danish", code: "da" },
	{ name: "Dutch", code: "nl" },
	{ name: "English", code: "en" },
	{ name: "Estonian", code: "et" },
	{ name: "Finnish", code: "fi" },
	{ name: "French", code: "fr" },
	{ name: "German", code: "de" },
	{ name: "Greek", code: "el" },
	{ name: "Hebrew", code: "he" },
	{ name: "Hindi", code: "hi" },
	{ name: "Hungarian", code: "hu" },
	{ name: "Indonesian", code: "id" },
	{ name: "Italian", code: "it" },
	{ name: "Japanese", code: "ja" },
	{ name: "Korean", code: "ko" },
	{ name: "Latvian", code: "lv" },
	{ name: "Lithuanian", code: "lt" },
	{ name: "Macedonian", code: "mk" },
	{ name: "Malay", code: "ms" },
	{ name: "Polish", code: "pl" },
	{ name: "Portuguese", code: "pt" },
	{ name: "Romanian", code: "ro" },
	{ name: "Russian", code: "ru" },
	{ name: "Serbian", code: "sr" },
	{ name: "Slovak", code: "sk" },
	{ name: "Slovenian", code: "sl" },
	{ name: "Spanish", code: "es" },
	{ name: "Swedish", code: "sv" },
	{ name: "Tagalog", code: "tl" },
	{ name: "Thai", code: "th" },
	{ name: "Turkish", code: "tr" },
	{ name: "Ukrainian", code: "uk" },
	{ name: "Urdu", code: "ur" },
	{ name: "Vietnamese", code: "vi" },
];
